name: frontend
description: A Flutter app for smarter food consumption.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  numberpicker: ^2.1.2
  flutter:
    sdk: flutter
  # google_ml_kit: ^0.16.3
  camera: ^0.10.5+2
  # flutter_tesseract_ocr: ^0.3.4
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_sliders: ^24.1.46

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/female.png
    - assets/male.png
    - assets/name.png
    - assets/other.png