// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQaJdStNpJKVHEWc3vFumA2EZqDm892-E',
    appId: '1:653857258907:web:2a2a3ba50317e28a61353e',
    messagingSenderId: '653857258907',
    projectId: 'consumewise-61e30',
    authDomain: 'consumewise-61e30.firebaseapp.com',
    storageBucket: 'consumewise-61e30.firebasestorage.app',
    measurementId: 'G-H3Q4F5KVTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxRfEkQiUjoO9Os1MKuQuchid3BmawvQ',
    appId: '1:653857258907:android:8a599e602a4fa4b461353e',
    messagingSenderId: '653857258907',
    projectId: 'consumewise-61e30',
    storageBucket: 'consumewise-61e30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJrWQGuYX1CN4UMqAu8r8kucggHgJAPA',
    appId: '1:653857258907:ios:ed0eeb8c8803104461353e',
    messagingSenderId: '653857258907',
    projectId: 'consumewise-61e30',
    storageBucket: 'consumewise-61e30.firebasestorage.app',
    iosClientId: '653857258907-f1kt9i59kgvpe7gkr737jc5irck5hh1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYJrWQGuYX1CN4UMqAu8r8kucggHgJAPA',
    appId: '1:653857258907:ios:ed0eeb8c8803104461353e',
    messagingSenderId: '653857258907',
    projectId: 'consumewise-61e30',
    storageBucket: 'consumewise-61e30.firebasestorage.app',
    iosClientId: '653857258907-f1kt9i59kgvpe7gkr737jc5irck5hh1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQaJdStNpJKVHEWc3vFumA2EZqDm892-E',
    appId: '1:653857258907:web:2b6a2a29547d8ea461353e',
    messagingSenderId: '653857258907',
    projectId: 'consumewise-61e30',
    authDomain: 'consumewise-61e30.firebaseapp.com',
    storageBucket: 'consumewise-61e30.firebasestorage.app',
    measurementId: 'G-44B48R3DCQ',
  );
}
